# Change these first
owner: helloallan # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: HelloAllan
    url: https://www.helloallan.com
  - name: EmptyChair App
    url: https://web.emptychair.app
  - name: EmptyChair Api
    url: https://api.emptychair.app/healthz
  - name: EmptyChair Marketing
    url: https://emptychair.app
  - name: AfterParty Marketing
    url: https://afterparty.chat
  - name: Grit
    url: https://trygrit.ai
  - name: Grit App
    url: https://app.trygrit.ai
  - name: AllRoads Dev
    url: https://allroads.dev
  - name: AllRoads To
    url: https://app.allroads.to
status-website:
  cname: status.helloallan.com
  name: Allan Status
